name: Build and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Keep manual trigger option

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller pywin32 winshell

      - name: Delete existing releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with PyInstaller
        run: |
          python build_exe.py
        env:
          PYTHONIOENCODING: utf-8
          PYTHONUTF8: 1

      - name: Generate version
        id: version
        run: |
          echo "build_version=v$(date +'%Y%m%d.%H%M')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.build_version }}
          name: TCP Server ${{ steps.version.outputs.build_version }}
          body: |
            Automated build from master branch
            
            Build Time: ${{ github.event.repository.updated_at }}
            Commit: ${{ github.sha }}
            Branch: ${{ github.ref_name }}
            
            **Changes:**
            ${{ github.event.head_commit.message }}
          files: release/*.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}