name: Build and Release Qt Integration

on:
  push:
    branches: [ feature/qt-integration ]
  pull_request:
    branches: [ feature/qt-integration ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: feature/qt-integration  # 确保检出正确的分支

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "importlib-metadata>=4.13.0"
          pip install pyinstaller pywin32 winshell
          pip install PyQt6

      - name: Delete existing releases from this branch
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 0
          delete_tags: true
          # 只删除这个分支的发布
          delete_tag_pattern: ^qt-integration-v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with PyInstaller
        run: |
          python build_exe.py
          cd release
          for %%f in (*.zip) do ren "%%f" "tool-list-qt.zip"
        shell: cmd
        env:
          PYTHONIOENCODING: utf-8
          PYTHONUTF8: 1

      - name: Generate version
        id: version
        run: |
          echo "build_version=qt-integration-v$(date +'%Y%m%d.%H%M')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.build_version }}
          name: Qt Integration Build ${{ steps.version.outputs.build_version }}
          body: |
            Qt Integration Branch Build

            Build Time: ${{ github.event.repository.updated_at }}
            Commit: ${{ github.sha }}
            Branch: feature/qt-integration

            **Changes:**
            ${{ github.event.head_commit.message }}
          files: release/tool-list-qt.zip
          draft: false
          prerelease: true  # 标记为预发布版本
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}