name: 构建 Windows 可执行文件

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          cache: pip

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 清理之前生成的 exe 文件
        run: |
          if (Test-Path "dist") { Remove-Item -Path "dist" -Recurse -Force }
          if (Test-Path "build") { Remove-Item -Path "build" -Recurse -Force }
          Get-ChildItem -Path "." -Filter "*.exe" | ForEach-Object { Remove-Item -Path $_.FullName -Force }

      - name: 运行构建脚本
        shell: cmd
        run: |
          chcp 65001
          set PYTHONIOENCODING=utf-8
          python build_exe.py
        env:
          PYTHONIOENCODING: utf-8
          PYTHONUTF8: 1

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: tcp-server-exe
          path: |
            dist/**/*.exe
            *.exe
          if-no-files-found: error